name: Playwright Tests
run-name: ${{ github.actor }} is taking upwithcrowd live ðŸš€
on:
  push:
    branches: [ upwithcrowd ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:
    - run: echo "ðŸŽ‰ Going Live!"
    - name: Release upwithcrowd
      run: ssh ubuntu "cd ~/frontend/upwithcrowd_prod && chmod 777 publish.sh && ./publish.sh 3599 upwithcrowd_prod"