name: Playwright Tests
run-name: ${{ github.actor }} is taking unirefund live ðŸš€
on:
  push:
    branches: [ unirefund ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:
    - run: echo "ðŸŽ‰ Going Live!"
    - name: Release unirefund
      run: ssh ubuntu "cd ~/frontend/prod_unirefund && chmod 777 publish.sh && ./publish.sh 3575 unirefund_prod"