name: Publish dev websites
run-name: ${{ github.actor }} is publishing projectt to dev üöÄ
on:
  push:
    branches: [ main, master ]
  # pull_request_target:
  #   branches: [ main, master ]
jobs:
  Publish_dev_websites:
    timeout-minutes: 60
    runs-on: self-hosted
    environment: upwithcrowd
    env: 
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
      AUTH_TRUST_HOST: ${{ secrets.TRUST_HOST }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}  
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      APPLICATION_NAME: ${{ vars.APPLICATION_NAME }}
      BASE_URL: ${{ secrets.BASE_URL }}
      PRIMARY_COLOR: ${{ vars.PRIMARY_COLOR }}
    steps:
    - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "üéâ The secret user is ${{ secrets.TEST_USERNAME }}"
    # - name: Make envfile
    #   uses: SpicyPizza/create-envfile@v2.0.3
    #   with:
    #     directory: "apps/web"
    #     file_name: .env
    #     fail_on_empty: true
    #     sort_keys: false
    #     envkey_TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
    #     envkey_APPLICATION_NAME: ${{ vars.APPLICATION_NAME }}
    #     envkey_PRIMARY_COLOR: ${{ vars.PRIMARY_COLOR }}
    # - name: show .env file
    #   run: | 
    #     cd .\apps\web 
    #     cat .env
    # - uses: actions/checkout@v4
    #   with:
    #     submodules: true
    # - uses: actions/setup-node@v4
    #   with:
    #     node-version: 20
    #     cache: 'pnpm'
    # - name: Install dependencies
    #   run: | 
    #     npm install -g pnpm
    #     pnpm install
    # - name: Install Playwright Browsers
    #   run: pnpm exec playwright install --with-deps
    # - name: Make envfile
    #   uses: SpicyPizza/create-envfile@v2.0.3
    #   with:
    #     directory: "apps/web"
    #     file_name: .env
    #     fail_on_empty: true
    #     sort_keys: false
    #     envkey_TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
    #     envkey_TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
    #     envkey_AUTH_TRUST_HOST: ${{ secrets.TRUST_HOST }}
    #     envkey_AUTH_SECRET: ${{ secrets.AUTH_SECRET }}  
    #     envkey_NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
    #     envkey_APPLICATION_NAME: ${{ vars.APPLICATION_NAME }}
    #     envkey_BASE_URL: ${{ secrets.BASE_URL }}
    #     envkey_PRIMARY_COLOR: ${{ vars.PRIMARY_COLOR }}
    # - name: build web app
    #   run: pnpm run build:web
    # - name: Start web app and wait for it to be ready
    #   run: pnpm run start:web 
    # - name: Run Playwright tests
    #   run: |
    #     cd .\apps\web 
    #     pnpm exec playwright test
    # - uses: actions/upload-artifact@v4
    #   if: ${{ !cancelled() }}
    #   with:
    #     name: playwright-report
    #     path: apps/web/playwright-report/
    #     retention-days: 30
    - name: Run unierfund
      run: ssh ubuntu "cd ~/frontend/unirefund_dev && chmod 777 publish.sh && ./publish.sh 1453 unirefund_web"
    - name: Run upwithcrowd
      run: ssh ubuntu "cd ~/frontend/upwithcrowd_dev && chmod 777 publish.sh && ./publish.sh 2020 upwithcrowd_web"
